<?php
if(basename($_SERVER['PHP_SELF']) === basename(__FILE__))
{
/**
 * 3/5/2015 11:29:09 AM
 * Please ignore awful debug code I needed to live edit the Javascript
 * and this is how I thought to do it. Everything marked with :

/**
 * XXX */

/* Should be removed or something. */
 
    define('FUX',true);
    error_reporting(0);
    ini_set('display_errors', 1);
    define('BUNZ_HTTP_DIR', '/bunzilla/');
    define('BUNZ_TPL_DIR', '../');
    $pageIcon = $pageTitle = $pageAction = $pageMode = '';
    $cat = ['description'=>1,'reproduce'=>1,'expected'=>1,'actual'=>1];
    echo '<html><body style="background: #fff !important; margin-top: 150px">';
}
?>
<!-- necessary for preview -->
<script src="<?= BUNZ_JS_DIR, 'highlight.js' ?>"></script>

<h1 class="<?= $pageIcon ?>"><?= $pageTitle ?></h1>
<form action="<?= BUNZ_HTTP_DIR, $pageAction ?>"
      id="withToolsModal"
      method="post"
      class="section">

    <div class="section category-<?= $cat['id'] ?>-text z-depth-3">
<?php
if($pageMode == 'new')
{
/**
 * XXX */
?>
         <div class="input-field">
            <i class="icon-mail prefix"></i>
            <input type="email" 
                    id="email" 
                    maxlength='255' 
                    name='email' 
                    value=<?= 
!defined('FUX') && $this->auth() 
? '"' . $_SERVER['PHP_AUTH_USER'] .'@'. $_SERVER['SERVER_NAME'] .'" disabled' 
: '"' . (isset($this->data['params']) ? $this->data['params']['email'] : '') . '" required' ?>>
            <span class="material-input"></span>
            <label for="email">email</label>
        </div>
<?php
}
/**
 * XXX */
if(!defined('FUX') && ($pageMode == 'new' || !isset($this->data['params']['comment_id'])))
{
?>
        <div class="input-field">
            <i class="icon-doc-text-inv prefix"></i>
            <input type="text"
                    maxlength="255"
                    id="subject"
                    name="subject"
                    autofocus
                    required
                    value="<?= isset($this->data['params']) ? $this->data['params']['subject'] : '' ?>">
            <span class="material-input"></span>
            <label for="subject">subject</label>
        </div>
<?php
}

$fields = [
    'description' => 'A synopsis or summary of the report you wish to submit',
    'reproduce'   => 'Instructions on how to create the behavior',
    'expected'    => 'The result, output, or other behavior you expect',
    'actual'      => 'The actual result, output, or other behavior that occurs',
];

if($pageMode == 'edit' && isset($this->data['params']['comment_id']))
    $fields = ['message' => 'Your unique and insightful voice'];

foreach($fields as $name => $placeholder)
{
    if(!$cat[$name])
        continue;
?>
        <div class="input-field">            
            <i class="icon-doc-text-inv prefix"></i>
            <textarea id="<?= $name ?>"
                      class="materialize-textarea" 
                      required 
                      name='<?= $name ?>'><?= !defined('FUX') && isset($this->data['params']) ? unfiltermessage($this->data['params'][$name]) : '' ?></textarea>
            <span class="material-input"></span>
            <label for="<?= $name ?>"><?= $name, ': ', $placeholder ?></label>
        </div>
<?php
}
?>

<div class="" style="margin: 1em 0 2em 0"></div>

        <p class="input-field">
            <input type="checkbox" id="disable_nlbr" name="disable_nlbr" value="1" <?= isset($_POST['disable_nlbr']) || (empty($_POST) && $pageMode == 'edit') ? ' checked' : ''?>>
            <label for="disable_nlbr">
            <i class="icon-paragraph" style="text-decoration: line-through"></i>Disable insertion of automatic linebreaks (&lt;br/&gt;)</label>
        </p>
        <p class="input-field">
            <input type="checkbox" id="literal_tabs" checked>
            <label for="literal_tabs">
            <i class="icon-tab"></i>Pressing the [TAB] key inserts &quot;\t&quot;</label>
        </p>
        <p class="input-field">
            <input type="checkbox" id="disable_html" name="disable_html" value="1" <?= isset($_POST['disable_html']) ? ' checked' : ''?>>
            <label for="disable_html">
            <i class="icon-cancel"></i>Disable HTML/bbCode entirely</label>
        </p>
        <div class="input-field center" style="margin-bottom: 1em">
            <div class="row">
                <a href="#toolsModal" 
                   data-for="<?= $name ?>"
                   class="col s6 m3 btn btn-flat waves-effect secondary-lighten-3 icon-code"
                   onclick="toggleModal(event)">toggle toolbar</a>
                <a href="#" class="col s6 m3 btn icon-magic waves-effect primary-base"
                    onclick="previewtest();">Preview <sup class='primary-darken-4'>NEW!</sup></a>
                <button type="reset" 
                        class="col s6 m3 btn btn-flat white shade-text icon-cancel waves-effect" <?php
if($pageMode == 'new' && empty($_POST))
 echo <<<JAVASCRIPT
onclick="(function(evt){if(!window.confirm('This action will delete everything you typed.')) evt.preventDefault()})(event)"
JAVASCRIPT;
?>><?= $pageMode == 'new' && empty($_POST) ? 'Clear' : 'Reset'?> Form</button>
                <button type="submit" 
                        class="col s6 m3 btn icon-plus waves-effect category-<?= $cat['id'] ?>-base">Submit</button>
            </div>

        </div>
<?php
/**
 * XXX */
if(!defined('FUX') && !isset($this->data['params']['comment_id']))
{
?>
        <div class="input-field collapsible no-select section" id="tagz" style="padding: 1em;">
            <div class="collapsible-header" style="position: absolute; width: 75%; z-index: 1">
                <i class="icon-tags prefix hide-on-small-only" style="margin: -1rem 0 0 -2rem"></i>
                <i class="icon-tags prefix hide-on-med-and-up" style="margin: -1rem 0 0 -1rem"></i>
                <p style="margin: -1rem 0 0 2rem; line-height: 3">Tag this post... 
                    <span class="icon-down-open-mini hide-on-active"></span>
                    <span class="icon-up-open-mini hide-on-inactive"></span>
                </p>
            </div>

            <div class="collapsible-body section z-depth-2 " style="margin: -1rem -1rem 0">
            <div style="padding-top: 1rem">&nbsp;</div>
            <div class="row section">
                <div class="divider" style="margin-bottom: 1rem"></div>
            </div>
            <div class="row section no-pad-top no-pad-bot">
<?php
//
// todo: figure out Javascript solution for this
// either <menu> or asJSON to do it
//
/**
 * XXX */
    $checked = isset($_POST['tags']) && is_array($_POST['tags']) 
             ? $_POST['tags'] 
             : (!defined('FUX') && isset($this->data['params']['tags']) 
               ? $this->data['params']['tags'] 
               : []
             );
    $i = 1;
/**
 * XXX */
    if(!defined('FUX')) {
    foreach($this->data['tags'] as $id => $tag)
    {
?>
    <div class="input-field col s6 m3 l1">
        <input type="checkbox" name="tags[]" id="tag_<?= $id ?>" value="<?= $id ?>"<?= in_array($id, $checked) ? ' checked' : ''?>>
        <label for="tag_<?= $id ?>"><small><?= $tag['title'] ?></small></label>
    </div>
<?php
        if($i%12 == 0 || $tag === end($this->data['tags']))
            echo '</div>', $tag !== end($this->data['tags']) ? '<div class="row section no-pad-top no-pad-bot">' : '';
        $i++;
    }}
?>
        </div>
        </div>
<?php
}
?>
    </div>
</form>
<div class="md-modal md-effect-7 z-depth-5" style="height: 100vh" id="preview_modal">
    <div class="md-content shade-text section" style="height: 100%; overflow: auto; ">
        <h2>Preview:</h2>
        <div id="preview_report"></div>
        <div class="section center" style="margin-bottom: 2em">
            <button class="btn btn-flat danger-base waves-effect waves-red icon-cancel" 
                    onclick="togglePreviewModal()">Close</button>
            <button id="fakesubmit" type="submit" class="btn icon-plus waves-effect category-<?= $cat['id'] ?>-base" onclick="document.forms['withToolsModal'].submit()">OK, Post This</button>
        </div>
    </div>
</div>
<script>
function togglePreviewModal() {
    var modal = document.getElementById('preview_modal').classList;
    if(modal.contains('md-show'))
    {
        setTimeout(function(){
            document.getElementById('preview_report').innerHTML = "";
            document.getElementById('fakesubmit').disabled = false;
        },1500);
    }
    modal.toggle('md-show');
}
function populateModal(field, value)
{
    var section = document.createElement('section'),
        h6 = document.createElement('h6'),
        blockquote = document.createElement('blockquote');

    section.setAttribute('class', 'section category-<?=$cat['id']?>');
    h6.appendChild(document.createTextNode(field));
    if(!value)
    {
        blockquote.classList.add('alert-text');
        blockquote.innerHTML = field + ' cannot be left blank!';
        document.getElementById('fakesubmit').disabled = true;
    } else {
        blockquote.innerHTML = value;
    }

    section.appendChild(h6);
    section.appendChild(blockquote);
    document.getElementById('preview_report').appendChild(section);
}
function previewtest()
{
    var formData = new FormData();
    formData.append('preview_report', true);
    formData.append('subject',document.getElementById('subject').value);
<?php
    foreach($fields as $name => $not_used)
        echo "\tformData.append('$name',document.getElementById('$name').value);\n";
?>
    var xhr = new XMLHttpRequest();
    xhr.open('POST', '<?= BUNZ_HTTP_DIR, $pageAction ?>?json');
    xhr.onreadystatechange = function() {
        if(xhr.readyState == 4)
        {
            var previewText = JSON.parse(xhr.responseText);
            for(field in previewText)
                populateModal(field, previewText[field]);
            $('pre code').each(function(i, block) {
                hljs.highlightBlock(block);
            });
            togglePreviewModal();
        }
    };
    xhr.send(formData);
}

</script>
<?php
/**
 * XXX */
if(defined('FUX'))
{
    require '../toolsModal.html';
    echo '<script src="../jquery-2.1.3.min.js"></script><style>@import "../assets/css/materialize.min.css";label{display:none !important}button{background: #fff !important}textarea{height: 10em !important}</style></body></html>';
} else {
     require BUNZ_TPL_DIR .'footer.inc.php';
}
