<h1 class="<?= $pageIcon ?>"><?= $pageTitle ?></h1>
<form action="<?= BUNZ_HTTP_DIR, $pageAction ?>"
      id="withToolsModal"
      method="post"
      class="section">

    <div class="section category-<?= $cat['id'] ?>-text z-depth-3">
<?php
if($pageMode == 'new')
{
?>
         <div class="input-field">
            <i class="icon-mail prefix"></i>
            <input type="email" 
                    id="email" 
                    maxlength='255' 
                    name='email' 
                    value=<?= 
$this->auth() 
? '"' . $_SERVER['PHP_AUTH_USER'] .'@'. $_SERVER['SERVER_NAME'] .'" disabled' 
: '"' . (isset($this->data['params']) ? $this->data['params']['email'] : '') . '" required' ?>>
            <span class="material-input"></span>
            <label for="email">email</label>
        </div>
<?php
}
if($pageMode == 'new' || !isset($this->data['params']['comment_id']))
{
?>
        <div class="input-field">
            <i class="icon-doc-text-inv prefix"></i>
            <input type="text"
                    maxlength="255"
                    id="subject"
                    name="subject"
                    autofocus
                    required
                    value="<?= isset($this->data['params']) ? $this->data['params']['subject'] : '' ?>">
            <span class="material-input"></span>
            <label for="subject">subject</label>
        </div>
<?php
}

$fields = [
    'description' => 'A synopsis or summary of the report you wish to submit',
    'reproduce'   => 'Instructions on how to create the behavior',
    'expected'    => 'The result, output, or other behavior you expect',
    'actual'      => 'The actual result, output, or other behavior that occurs',
];

if($pageMode == 'edit' && isset($this->data['params']['comment_id']))
    $fields = ['message' => 'Your unique and insightful voice'];

foreach($fields as $name => $placeholder)
{
    if(!$cat[$name])
        continue;
?>
        <div class="input-field">            
            <i class="icon-doc-text-inv prefix"></i>
            <textarea id="<?= $name ?>"
                      class="materialize-textarea" 
                      required 
                      name='<?= $name ?>'><?= isset($this->data['params']) ? unfiltermessage($this->data['params'][$name]) : '' ?></textarea>
            <span class="material-input"></span>
            <label for="<?= $name ?>"><?= $name, ': ', $placeholder ?></label>
        </div>
<?php
}
?>

<div class="" style="margin: 1em 0"></div>

        <p class="input-field">
            <input type="checkbox" id="disable_nlbr" name="disable_nlbr" value=1"<?= isset($_POST['disable_nlbr']) || (empty($_POST) && $pageMode == 'edit') ? ' checked' : ''?>>
            <label for="disable_nlbr">
            <i class="icon-paragraph" style="text-decoration: line-through"></i>Disable insertion of automatic linebreaks (&lt;br/&gt;)</label>
        </p>
<?php
if(!isset($this->data['params']['comment_id']))
{
?>
        <div class="input-field collapsible no-select section" id="tagz" style="padding: 1em;">
            <div class="collapsible-header" style="position: absolute; z-index: 1000; width: 75%">
                <i class="icon-tags prefix hide-on-small-only" style="margin: -1rem 0 0 -2rem"></i>
                <i class="icon-tags prefix hide-on-med-and-up" style="margin: -1rem 0 0 -1rem"></i>
                <p style="margin: -1rem 0 0 2rem; line-height: 3">Tag this post... 
                    <span class="icon-down-open-mini hide-on-active"></span>
                    <span class="icon-up-open-mini hide-on-inactive"></span>
                </p>
            </div>

            <div class="collapsible-body section z-depth-2 " style="margin: -1rem -1rem 0">
            <div style="padding-top: 1rem">&nbsp;</div>
            <div class="row section">
                <div class="divider" style="margin-bottom: 1rem"></div>
            </div>
            <div class="row section no-pad-top no-pad-bot">
<?php
//
// todo: figure out Javascript solution for this
// either <menu> or asJSON to do it
//
    $checked = isset($_POST['tags']) && is_array($_POST['tags']) 
             ? $_POST['tags'] 
             : (isset($this->data['params']['tags']) 
               ? $this->data['params']['tags'] 
               : []
             );
    $i = 1;
    foreach($this->data['tags'] as $id => $tag)
    {
?>
    <div class="input-field col s6 m3 l1">
        <input type="checkbox" name="tags[]" id="tag_<?= $id ?>" value="<?= $id ?>"<?= in_array($id, $checked) ? ' checked' : ''?>>
        <label for="tag_<?= $id ?>"><small><?= $tag['title'] ?></small></label>
    </div>
<?php
        if($i%12 == 0 || $tag === end($this->data['tags']))
            echo '</div>', $tag !== end($this->data['tags']) ? '<div class="row section no-pad-top no-pad-bot">' : '';
        $i++;
    }
?>
        </div>
        </div>
<?php
}
?>
        <div class="input-field center">
            <a href="#toolsModal" data-for="<?= $name ?>" class="btn-flat waves-effect secondary-lighten-3" onclick="toggleModal(event)"><i class="icon-code"></i> toggle toolbar</a>
            <button type="reset" class="btn-flat white shade-text icon-cancel waves-effect"<?php
if($pageMode == 'new' && empty($_POST))
 echo <<<JAVASCRIPT
onclick="(function(evt){if(!window.confirm('This action will delete everything you typed.')) evt.preventDefault()})(event)"
JAVASCRIPT;
?>><?= $pageMode == 'new' && empty($_POST) ? 'Clear' : 'Reset'?> Form</button>
            <button type="submit" class="btn icon-plus waves-effect category-<?= $cat['id'] ?>-base">Submit</button>
        </div>
    </div>
</form>
<?php
require BUNZ_TPL_DIR .'footer.inc.php';
